### ISSUE TITLE
sqlalchemy.exc.IntegrityError

### ISSUE THREAD

**Issue by mzfr** [blabla1337/skf-labs#55]
While building the dockerfile for graphql-IDOR challenge I am getting a sqlalchemy.exc.IntegrityError

```bash
➜ sudo docker build .
Sending build context to Docker daemon  2.048kB
Step 1/8 : FROM alpine:3.7
 ---> 6d1ef012b567
Step 2/8 : MAINTAINER Davide Cioccia <d.cioccia@dcodx.com>
 ---> Using cache
 ---> 95ba54cc967e
Step 3/8 : RUN apk update --no-cache && apk add python3     python3-dev     py3-pip     bash     git
 ---> Using cache
 ---> 5f4cb88ed81f
Step 4/8 : RUN git clone https://github.com/blabla1337/skf-labs.git
 ---> Using cache
 ---> 232cff693419
Step 5/8 : WORKDIR /skf-labs/graphql-IDOR
 ---> Using cache
 ---> 75195b284e90
Step 6/8 : RUN pip3 install -r requirements.txt
 ---> Using cache
 ---> 58b625454a81
Step 7/8 : RUN python3 populate-database.py
 ---> Running in c5f965a913fd
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: users.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "populate-database.py", line 60, in <module>
    db.session.commit()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2479, in flush
    self._flush(objects)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2577, in _flush
    flush_context.execute()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1137, in _emit_insert_statements
    statement, params
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: users.username
[SQL: INSERT INTO users (username, password, "isAdmin") VALUES (?, ?, ?)]
[parameters: ('johndoe', 'password1', 0)]
(Background on this error at: http://sqlalche.me/e/gkpj)
The command '/bin/sh -c python3 populate-database.py' returned a non-zero code: 1
```

**Comment by blabla1337** [comment]
yes I saw and fixed it, thanks :)

**Comment by shadihh9** [comment]
i have problem when  solve challange graphql injection 
![i have problem](https://user-images.githubusercontent.com/22076930/92466334-9dbf2080-f1d8-11ea-8c58-a76a7f4e006b.png)
